apiVersion: v1
kind: Service
metadata:
  name: age-calc-service
  labels:
    app: age-calc
spec:
  type: NodePort
  selector:
    app: age-calc
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
    nodePort: 30005
